= taboo4 serverless backend
:toc: preamble
:toclevels: 5
:sample-url: https://amt0758ulj.execute-api.eu-central-1.amazonaws.com/dev
:sample-api-key: DjOp5Yag351q8hQuA8QEA5h8A7k6ZkwX9Wl8EUS5

Description of the backend for the _taboo4_ tagged bookmark service.


== Technology

The backend is implemented in Amazon AWS using Lambda functions based on a NodeJS 8.10 runtime and DynamoDB as a storage backend. The access to the lambda functions is by an API Gateway. The whole deployment is managed by using the https://serverless.com[serverless framework].  In this document the short command `sls` is used instead of `serverless`.

The Lambda functions are written in Javascript, for the tests _mocha_, _chaijs_ and _sinon_ are used.


== Setup

=== AWS credentials

efore testing against a local Dynamo DB or deploying the AWS credentials need to be set up,`/bookmark` endpoint:

so that the relevant environment variables are set:

* AWS_PROFILE
* AWS_REGION
* AWS_DEFAULT_REGION=eu-central-1

== API functions

.API Key
When the service is deployed with `sls deploy` an API Key is generated, the value is shown in the output. This API key must be passed as the value of a HTTP header named `x-api-key`, otherwise the API Gateway rejects the call with an error code 403


The API offers the following functions (examples are shown with an API Gateway endpoint deployed to a _dev_ stage and some API key ):

=== Create a bookmark

A bookmark is created by POSTing a bookmark object to the `/bookmark` endpoint:

.curl
[source,shell,subs="attributes"]
----
curl -X "POST" "{sample-url}/bookmark" \
     -H 'x-api-key: {sample-api-key}' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "url": "https://www.sothawo.com",
  "title": "sothawo",
  "tags": [
    "cool",
    "must-see"
  ]
}'
----

.httpie
[source,shell,subs="attributes"]
----
http --json POST '{sample-url}/bookmark' \
    'x-api-key':'{sample-api-key}' \
    'Content-Type':'application/json; charset=utf-8' \
    url="https://www.sothawo.com" \
    title="sothawo" \
    tags:="[
  \"cool\",
  \"must-see\"
]"
----

On Success a status code of *201* is returned with a body containing the created bookmark:

.Response
[source,json]
----
{
  "url": "https://www.sothawo.com",
  "title": "sothawo",
  "id": "4e838186c8e40cbe9ec698501f223608",
  "tags": [
    "cool",
    "must-see"
  ]
}
----

=== Retrieve a bookmark

A bookmark is retrieved by GETing a bookmark id on the `/bookmark/{id}` endpoint:

.curl
[source,shell,subs="attributes"]
----
curl -X "GET" "{sample-url}/bookmark/4e838186c8e40cbe9ec698501f223608" \
     -H 'x-api-key: {sample-api-key}'
----

.httpie
[source,shell,subs="attributes"]
----
http GET '{sample-url}/bookmark/4e838186c8e40cbe9ec698501f223608' \
    'x-api-key':'{sample-api-key}'
----

On Success a status code of *200* is returned with a body containing the bookmark:

.Response
[source,json]
----
{
  "url": "https://www.sothawo.com",
  "title": "sothawo",
  "id": "4e838186c8e40cbe9ec698501f223608",
  "tags": [
    "cool",
    "must-see"
  ]
}
----

=== Retrieve all bookmarks

All bookmarks are retrieved by GETing  the `/bookmarks` endpoint:

.curl
[source,shell,subs="attributes"]
----
curl -X "GET" "{sample-url}/bookmarks" \
     -H 'x-api-key: {sample-api-key}'
----

.httpie
[source,shell,subs="attributes"]
----
http GET '{sample-url}/bookmarks' \
    'x-api-key':'{sample-api-key}'
----

On Success a status code of *200* is returned with a body containing an array of bookmarks:

.Response
[source,json]
----
[
  {
    "url": "https://www.codecentric.de",
    "title": "codecentric",
    "id": "b3e1c377adf8a80fcfda8ed100a8f886",
    "tags": [
      "active",
      "work"
    ]
  },
  {
    "url": "https://www.sothawo.com",
    "title": "sothawo",
    "id": "4e838186c8e40cbe9ec698501f223608",
    "tags": [
      "cool",
      "must-see"
    ]
  },
  {
    "url": "https://www.hlx.com",
    "title": "hlx",
    "id": "afeb91fd58e0ebc0b4b471a9320a8c27",
    "tags": [
      "inactive",
      "work"
    ]
  }
]
----

=== Retrieve all tags

All tags are retrieved by GETing  the `/tags` endpoint:

.curl
[source,shell,subs="attributes"]
----
curl -X "GET" "{sample-url}/tags" \
     -H 'x-api-key: {sample-api-key}'
----

.httpie
[source,shell,subs="attributes"]
----
http GET '{sample-url}/tags' \
    'x-api-key':'{sample-api-key}'
----

On Success a status code of *200* is returned with a body containing an array of tags (which might be empty):

.Response
[source,json]
----
[
  "active",
  "cool",
  "inactive",
  "must-see",
  "work"
]
----

=== Query for bookmarks

A query to retrieve bookmarks must be POSTed to the `/bookmarks/query` endpoint. The query parameters must be sent as the request body. At the moment the only supported request parameters are tags:

.curl
[source,shell,subs="attributes"]
----
curl -X "POST" "{sample-url}/bookmarks/query" \
     -H 'x-api-key: {sample-api-key}' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "tags": [
    "work"
  ]
}'
----

.httpie
[source,shell,subs="attributes"]
----
http --json POST '{sample-url}/bookmarks/query' \
    'x-api-key':'{sample-api-key}' \
    'Content-Type':'application/json; charset=utf-8' \
    tags:="[
  \"work\"
]"
----

On Success a status code of *200* is returned with a body containing an array of bookmarks (which might be empty):

[source, json]
----
[
  {
    "url": "https://www.codecentric.de",
    "title": "codecentric",
    "id": "b3e1c377adf8a80fcfda8ed100a8f886",
    "tags": [
      "active",
      "work"
    ]
  },
  {
    "url": "https://www.hlx.com",
    "title": "hlx",
    "id": "afeb91fd58e0ebc0b4b471a9320a8c27",
    "tags": [
      "inactive",
      "work"
    ]
  }
]
----

== Testing

=== Unit Tests

unit tests can be run with

[source,shell]
----
$ npm test
----

=== Local integration tests

Local test can be done either by using the `sls invoke local` command or by using SAM local.
The AWS infrastructure components are provided using the _localstack_ image that provides AWS services in a local docker container.

The configuration files and this document assume that for local test the stage value is set to _local_.

==== Docker

First a network for the container must be created:

[source, shell]
----
docker network create taboo4
----

==== DynamoDB

Start localstack (all in one line):

[source,shell]
----
$ TMPDIR=/private$TMPDIR SERVICES=dynamodb DEFAULT_REGION=eu-central-1 PORT_WEB_UI=28080 docker-compose up & 
----

To access this instance, AWS credentials must be set, any fake credential in the environment will do.

==== Running functions locally

To test the functions locally, the DynamoDB endpoint must be passed as an environment variable to the serverless command, first the `sls` calls are shown.

[source,shell]
----
$ DYNAMODB_URL=http://localhost:4569 sls invoke local -f config -stage=local
----

==== Preparing the table in the local DynamoDB

===== Create the table

To create the table, a serverless function is implemented which can be called like so:

[source,shell]
----
$ DYNAMODB_URL=http://localhost:4569 sls invoke local -f createTable -stage=local
----

This function is not available via an endpoint and can only be invoked with the `sls` command.

===== Listing tables

[source,shell]
----
$ aws dynamodb list-tables --endpoint-url http://localhost:4569
----

===== Delete the table

The table can be deleted by running:

[source,shell]
----
$ DYNAMODB_URL=http://localhost:4569 sls invoke local -f deleteTable -stage=local
----

This function as well is only callable by using the `sls` command.

===== Add an entry to the table

There is a sample event in the _testdata_ directory with which a bookmark can be created:

[source,shell]
----
$ DYNAMODB_URL=http://localhost:4569 sls invoke local -f postBookmark -stage=local -p testdata/postBookmarkEvent.json
----

===== List table content

Only feasible for small tables in local development:

[source,shell]
----
$ aws dynamodb scan --table-name taboo4-local --endpoint=http://localhost:4569
----

==== Using SAM local

SAM local starts a docker container when running the functions. Therefore for the SAM local environment, the database host is **not** _localhost_ but _backend_localstack_1_.
.Installation

[source,shell]
----
$ pip install --user aws-sam-cli
----

.Starting SAM local

[source,shell]
----
sam local start-api --docker-network taboo4 [--skip-pull-image]
----

This starts an API gateway with all the resources configured in _template.yaml_

== Deployment

The service with all it's functions and resources is deployed to AWS with:

[source,shell]
----
$ sls deploy
----

By default, it is deployed to the _dev_ stage, to change this, the stage can be set with an argument:

[source,shell]
----
$ sls -stage=prod deploy
----

After deployment a simple test to do is to call the _config_ function:

[source,shell]
----
$ sls -stage=prod invoke config
----
