= taboo4 serverless backend
:toc: preamble
:toclevels: 5
:sample-url: https://amt0758ulj.execute-api.eu-central-1.amazonaws.com/dev
:sample-api-key: DjOp5Yag351q8hQuA8QEA5h8A7k6ZkwX9Wl8EUS5

Description of the backend for the _taboo4_ tagged bookmark service.


The whole taboo4 backend is implemented with AWS Lambdas and a DynamoDB. It is set up with use of the  https://servelsess.com[serveless framework]. In this document the short command `sls` is used instead of `serverless`.

== Setup

=== AWS credentials

efore testing against a local Dynamo DB or deploying the AWS credentials need to be set up,`/bookmark` endpoint:

so that the relevant environment variables are set:

* AWS_PROFILE
* AWS_REGION
* AWS_DEFAULT_REGION=eu-central-1

== API functions

.API Key
When the service is deployed with `sls deploy` an API Key is generated, the value is shown in the output. This API key must be passed as the value of a HTTP header named `x-api-key`, otherwise the API Gateway rejects the call with an error code 403


The API offers the following functions (examples are shown with an API Gateway endpoint deployed to a _dev_ stage and some API key ):

=== Create a Bookmark

A bookmark is created by POSTing a bookmark object to the `/bookmark` endpoint:

.curl
[source,shell,subs="attributes"]
----
curl -X "POST" "{sample-url}/bookmark" \
     -H 'x-api-key: {sample-api-key}' \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "url": "https://www.sothawo.com",
  "title": "sothawo",
  "tags": [
    "cool",
    "must-see"
  ]
}'
----

.httpie
[source,shell,subs="attributes"]
----
http --json POST '{sample-url}/bookmark' \
    'x-api-key':'{sample-api-key}' \
    'Content-Type':'application/json; charset=utf-8' \
    url="https://www.sothawo.com" \
    title="sothawo" \
    tags:="[
  \"cool\",
  \"must-see\"
]"
----

On Success a status code of *201* is returned with a body containing the created bookmark:

.Response
[source,json]
----
{
  "url": "https://www.sothawo.com",
  "title": "sothawo",
  "id": "4e838186c8e40cbe9ec698501f223608",
  "tags": [
    "cool",
    "must-see"
  ]
}
----

=== Retrieve a Bookmark

A bookmark is retrieved by GETing a bookmark id on the `/bookmark/{id}` endpoint:

.curl
[source,shell,subs="attributes"]
----
curl -X "GET" "{sample-url}/bookmark/4e838186c8e40cbe9ec698501f223608" \
     -H 'x-api-key: {sample-api-key}'
----

.httpie
[source,shell,subs="attributes"]
----
http GET '{sample-url}/bookmark/4e838186c8e40cbe9ec698501f223608' \
    'x-api-key':'{sample-api-key}'
----

On Success a status code of *200* is returned with a body containing the bookmark:

.Response
[source,json]
----
{
  "url": "https://www.sothawo.com",
  "title": "sothawo",
  "id": "4e838186c8e40cbe9ec698501f223608",
  "tags": [
    "cool",
    "must-see"
  ]
}
----

IMPORTANT: **TODO** add other calls

== Testing

=== Unit Tests

unit tests can be run with

[source,shell]
----
$ npm test
----

=== Local integration tests

==== DynamoDB

To set up DynamoDB running in docker, exposed to port 8000:

[source,shell]
----
$ docker run --name dynamodb -d -p 8000:8000 amazon/dynamodb-local
----

To access this instance, AWS credentials must be set, any fake credential in the environment will do.

==== Running functions locally

To test the functions locally, the DynamoDB endpoint must be passed as an environment variable to the serverless command, i.e.:

[source,shell]
----
$ DYNAMODB_URL=http://localhost:8000 sls invoke local -f config
----

==== Preparing the table in the local DynamoDB

===== Create the table

To create the table, a serverless function is implemented which can be called like so:

[source,shell]
----
$ DYNAMODB_URL=http://localhost:8000 sls invoke local -f createTable
----

This function is not available via an endpoint and can only be invoked with the `sls` command.

===== Listing tables

[source,shell]
----
aws dynamodb list-tables --endpoint-url http://localhost:8000
----

===== Delete the table

The table can be deleted by running:

[source,shell]
----
$ DYNAMODB_URL=http://localhost:8000 sls invoke local -f deleteTable
----

This function as well is only callable by using the `sls` command.

===== Add an entry to the table

There is a sample event in the _testdata_ directory with which a bookmark can be created:

[source,shell]
----
$ DYNAMODB_URL=http://localhost:8000 sls invoke local -f postBookmark -p testdata/postBookmarkEvent.json
----

===== List table content

Only feasible for small tables in local development:

[source,shell]
----
$ aws dynamodb scan --table-name taboo4-dev --endpoint=http://localhost:8000
----

== Deployment

The service with all it's functions and resources is deployed to AWS with:

[source,shell]
----
$ sls deploy
----

By default, it is deployed to the _dev_ stage, to change this, the stage can be set with an argument:

[source,shell]
----
$ sls -stage=prod deploy
----

After deployment a simple test to do is to call the _config_ function:

[source,shell]
----
$ sls -stage=prod invoke config
----
