
service: taboo4

package:
  exclude:
    - "testdata/**"
    - "**/*.spec.js"
    - "README.adoc"

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  stackName: ${self:service}-${self:provider.stage}
  tags:
    app: "taboo4"
  environment:
    DYNAMODB_TABLE: ${self:provider.stackName}
  apiKeys:
    - ${self:provider.stackName}
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 100
      rateLimit:  50
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  config:
    handler: aws/config.handler
    events:
      - http:
          path: config
          method: get
          cors: true
          private: true
  postBookmark:
    handler: aws/bookmark_post.handler
    events:
      - http:
          path: bookmark
          method: post
          cors: true
          private: true
  getBookmark:
    handler: aws/bookmark_get.handler
    events:
      - http:
          path: bookmark/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
          cors: true
          private: true
  getBookmarks:
    handler: aws/bookmarks_get.handler
    events:
      - http:
          path: bookmarks
          method: get
          cors: true
          private: true
  createTable:
    handler: aws/dynamodb_createtable.handler
  deleteTable:
    handler: aws/dynamodb_deletetable.handler

resources:
  Resources:
    Taboo4DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
#      DeletionPolicy: Retain
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: partition
            AttributeType: S
          -
            AttributeName: sort
            AttributeType: S
        KeySchema:
          -
            AttributeName: partition
            KeyType: HASH
          -
            AttributeName: sort
            KeyType: RANGE
        # could be changed to OnDemand in AWS console, not possible in Cloudformation at the moment
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
